### ISSUE TITLE
valgrind/cachegrind.h does not exist on Arch Linux

### ISSUE THREAD

**Issue by mohe2015** [2dav/crabgrind#3]
Hi, it seems like valgrind/cachegrind.h as introduced in https://github.com/2dav/crabgrind/commit/ad39a2128ba55abde697e62b42a76e36e8fe660c does not exist in the Arch Linux https://archlinux.org/packages/extra/x86_64/valgrind/files/ package. Should this be fixed on the Arch Linux side or in this package?
```
The following warnings were emitted during compilation:

warning: crabgrind@0.1.10: export.c:2:10: fatal error: valgrind/cachegrind.h: No such file or directory
warning: crabgrind@0.1.10:     2 | #include <valgrind/cachegrind.h>
warning: crabgrind@0.1.10:       |          ^~~~~~~~~~~~~~~~~~~~~~~
warning: crabgrind@0.1.10: compilation terminated.

error: failed to run custom build command for `crabgrind v0.1.10`

Caused by:
  process didn't exit successfully: `/home/moritz/Documents/project/target/release/build/crabgrind-0b7b82b707333898/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=export.c
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/moritz/Documents/project/target/release/build/crabgrind-c9c6769248176212/out/export.o" "-c" "export.c"
  cargo:warning=export.c:2:10: fatal error: valgrind/cachegrind.h: No such file or directory

  cargo:warning=    2 | #include <valgrind/cachegrind.h>

  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~

  cargo:warning=compilation terminated.

  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/moritz/Documents/project/target/release/build/crabgrind-c9c6769248176212/out/export.o" "-c" "export.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
```

**Comment by 2dav** [comment]
Hey! `valgrind/cachegrind.h` is introduced in Valgrind 3.22, see #1 and [doc](https://valgrind.org/docs/manual/cg-manual.html#cg-manual.clientrequests) for details. 

To use `crabgrind` with Valgrind versions prior to `3.22`, you can use [crabgrind 0.1.9](https://crates.io/crates/crabgrind/0.1.9).

**Comment by 2dav** [comment]
Closing in favor of "Compatibility" section in the repo "readme".
